#!/usr/bin/env python3

import subprocess

from scapy.all import ARP, Ether, sniff, srp

def get_mac(ip):
    p = Ether(dst='ff:ff:ff:ff:ff:ff')/ARP(pdst=ip)
    result = srp(p, timeout=3, verbose=False)[0]
    if not result:
        return None
    return result[0][1].hwsrc

def process(packet):
    if packet.haslayer(ARP):
        if packet[ARP].op == 2:
            try:                
                real_mac = get_mac(packet[ARP].psrc)
                response_mac = packet[ARP].hwsrc
                if real_mac and real_mac != response_mac:
                       subprocess.run(["iptables", "-A", "INPUT", "-m", "mac", "--mac-source", response_mac, "-j", "DROP"], check=False)
            except IndexError:
                pass

sniff(store=False, prn=process)
